#!/usr/bin/env bash
# read passwd file and extract fields

while IFS=: read -r username password uid gid more_info home_dir shell; do
	echo "The user $username is part of the $gid gang, lives in $home_dir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $more_info"
done < /etc/passwd
