#!/usr/bin/env bash
# display content of current directory

for file in *; do
# check if file is not hidden and the file has dash in its name
if [[ ! "$file" == .* && "$file" =~ - ]]; then
		name=$(echo "$file" | cut -d '-' -f 2-)
  		echo "$name"
     	fi
done
